spring:
  application:
    name: b07-prism

  cache:
    type: none # please comment in production :D

  thymeleaf:
    cache: false # and this too

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

prism:
  storage:
    proposals: ${PRISM_PROPOSAL_STORAGE:./storage/proposals}

  scheduler:
    reservation-lifecycle-ms: ${PRISM_RESERVATION_LIFECYCLE_MS:60000}